name: "🌀 Multiversal Anomaly Report"
description: "Submit a dream, Mandela Effect, glitch, or any experience that may indicate interdimensional resonance."
title: "[Anomaly] - "
labels: MRT report
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🧠 Multiversal Resonance Tracker – Anomaly Report
        Please answer the following questions as best you can. Your data helps us track potential synchronizations across realities.

  - type: dropdown
    id: anomaly_type
    attributes:
      label: "What type of anomaly are you reporting?"
      options:
        - Dream Experience
        - Mandela Effect
        - Time Glitch
        - Parallel Self Encounter
        - Reality Inconsistency
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "📝 Describe the anomaly in detail"
      description: "Tell us exactly what happened, how it felt, and what made it stand out."
      placeholder: "I woke up remembering a city that doesn’t exist, but it felt more real than this one..."
    validations:
      required: true

  - type: input
    id: date_time
    attributes:
      label: "📅 Date and Time of Event"
      description: "When did this happen? If unknown, give your best guess."
      placeholder: "e.g., 2025-06-10 03:45 AM"
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: "🌍 Location"
      description: "City, country, or approximate coordinates where the anomaly occurred."
      placeholder: "New York City, USA"
    validations:
      required: false

  - type: textarea
    id: dream_analysis
    attributes:
      label: "🌙 Dream-Specific (if applicable)"
      description: "Describe the dream content. Was the world familiar? Did you feel like a different version of yourself? Were there repeating symbols?"
    validations:
      required: false

  - type: textarea
    id: mandela_effect
    attributes:
      label: "🌀 Mandela Effect Details (if applicable)"
      description: "What do you remember differently than how it exists now? Brands, quotes, historical events, etc."
    validations:
      required: false

  - type: textarea
    id: time_glitch
    attributes:
      label: "⏳ Time Distortion or Glitch (if applicable)"
      description: "Did you experience any lost time, repeats, fast-forwarding, or changes in how time flowed?"
    validations:
      required: false

  - type: textarea
    id: identity_shift
    attributes:
      label: "🧬 Parallel Self or Identity Shift (if applicable)"
      description: "Did you feel like someone else? Recall memories you never made? Notice changes in your personality or path?"
    validations:
      required: false

  - type: input
    id: intensity
    attributes:
      label: "⚡ Intensity Score (1–10)"
      description: "How emotionally or mentally intense was the experience?"
      placeholder: "e.g., 8"
    validations:
      required: true

  - type: textarea
    id: additional_data
    attributes:
      label: "📎 Additional Notes or Metadata"
      description: "Feel free to include anything else: links, photos, device used, or follow-up thoughts."
    validations:
      required: false
